### ISSUE TITLE
Bug: unused union fragments raise AttributeError

### ISSUE THREAD

**Issue by EDjur** [mirumee/ariadne-codegen#161]
Hi again and thanks for all the great work in this project 👋 Found a small bug related to unions and unused fragments (**on latest main**):

Given the following schema:
```
union Cat = BlackCat | WhiteCat

type BlackCat {
  a: String!
}

type WhiteCat {
  b: String!
}

type MyTypeA {
  id: String!
}

type Query {
  myTypeA(id: String!): MyTypeA
}
```

And the following operations:
```
fragment CatDetails on Cat {
  __typename

  ... on BlackCat {
    a
  }

  ... on WhiteCat {
    b
  }
}

query GetMyTypeA($id: String!) {
  myTypeA(id: $id) {
    id
  }
}
```

The codegen crashes with the following:
```
  File ".../ariadne_codegen/client_generators/result_types.py", line 347, in _get_field_from_schema
    return cast(GraphQLObjectType, self.schema.type_map[type_name]).fields[
AttributeError: 'GraphQLUnionType' object has no attribute 'fields'
```

Note that `MyTypeA` isn't likely related to what's going on here, I just added it to be able to run the codegen properly. Also note that the `CatDetails` fragment isn't used anywhere but still causes the crash.

Some additional notes: If I change the schema (and keep the operations the same) to the following, it starts working. So it must be something related to `unions` specifically.
```
interface Cat {
  color: String!
}

type BlackCat implements Cat {
  color: String!
  a: String!
}

type WhiteCat implements Cat {
  color: String!
  b: String!
}

type MyTypeA {
  id: String!
}

type Query {
  myTypeA(id: String!): MyTypeA
}
```

**Comment by mat-sop** [comment]
Hey, thanks for creating this issue. We don't generate models for fragments with inline fragments in top level of selection, but instead we "unpack" them (eg. [query](https://github.com/mirumee/ariadne-codegen/blob/main/tests/main/clients/inline_fragments/queries.graphql#L116) and [result models](https://github.com/mirumee/ariadne-codegen/blob/main/tests/main/clients/inline_fragments/expected_client/query_with_fragment_on_union.py))
For interface it produces invalid model, so It doesn't truly work but by accident it doesn't raise exception either.

I looks like exception is thrown because, right now (on latest main) we look through fragments while we parse operations, when we encounter such a fragment we exclude it from `fragments.py`. When fragment is unused it can't be excluded :/ We should change this logic to handle unused fragments.

**Comment by EDjur** [comment]
Cool! This isn't a blocker for me. I just spent some time trying to figure out what was causing the `AttributeError` as it wasn't very clear. So I think yeah just better handling and/or error messages is a good solution :)
