### ISSUE TITLE
Need to upgrade or add support for Pydantic version > 2

### ISSUE THREAD

**Issue by mohyt** [mirumee/ariadne-codegen#250]
ariadne-codegen dependent on pydantic but only compatible with version >= 1.10.4 to < 2.0. Also acryl-datahub SDK but only compatible with version of >= 2.0 to < 3.0

**Comment by bombsimon** [comment]
What version are you using? Since [`0.8.0`](https://github.com/mirumee/ariadne-codegen/releases/tag/0.8.0) `ariadne-codegen` is using `pydantic` v2 and so do we after bumping to this version. The current dependency is noted as `>=2.0.0,<3.0.0`.

https://github.com/mirumee/ariadne-codegen/blob/184f9f2c99b58bc41af954f52e2644bc032c9e95/pyproject.toml#L29

**Comment by mat-sop** [comment]
@mohyt I'm closing this issue, as @bombsimon wrote since `0.8.0` we're supporting v2. Feel free to reopen or create a new issue if needed.
