### ISSUE TITLE
Feature Suggestion: Separate subdirectory for result types

### ISSUE THREAD

**Issue by alzex3** [mirumee/ariadne-codegen#262]
Dear Contributors,

First and foremost, I want to extend my gratitude to all the contributors. This library has been incredibly beneficial in my work.

In my daily usage, I often find myself needing to check generated client enums, inputs, fragments, and the client itself. However, it's hard to navigate through the package because of the hundreds of modules, with result types mixed in. This usually requires a lot of searching or scrolling through the package directory.

To enhance usability and organization, I propose adding an option to collect result types in a separate subdirectory. This adjustment would make the generated package directory more intuitive and accessible. 

[I've created a PR to implement this feature.](https://github.com/mirumee/ariadne-codegen/pull/261) I look forward to your feedback and hope you will consider this enhancement positively.

<img width="1512" alt="separate_types_dir_2" src="https://github.com/mirumee/ariadne-codegen/assets/87263895/c8702508-5c83-4748-b44d-f236de23ac68">
<img width="1512" alt="separate_types_dir_1" src="https://github.com/mirumee/ariadne-codegen/assets/87263895/fbdc789b-0a38-4256-beae-a510e8df33c4">

**Comment by rafalp** [comment]
Hello,

I am little scared at the scale of changes in the PR in question, but I understand its mostly tests. But I would prefer this feature to be achieved as a plugin in `contrib` directory, and not another feature in core generator. Is there anything missing in plugin system that would prevent that?

Its great for the users when the package has a knob for everything, but at the same time such package has large maintenance burden. Which is why we are trying to achieve as much as possible with plugins.

**Comment by alzex3** [comment]
Hello! I understand your position. Thanks for response.

**Comment by rafalp** [comment]
Thank you for understaing. I am sorry I can't offer anything better. But I will welcome a PR with changes enabling client layout customization with a plugin.
